lil_works_message_form:
    path:     /
    defaults: { _controller: LilworksMessageBundle:Default:form }
lil_works_message_sent:
    path:     /{id}/sent
    defaults: { _controller: LilworksMessageBundle:Default:sent }
